// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load environment variables from .env
config({ path: '.env' });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use non-pooling connection for migrations
    url: process.env.POSTGRES_URL_NON_POOLING || process.env.DATABASE_URL || "",
  },
});
